### ISSUE TITLE
tag_match_score for middle Europe needs improvements

### ISSUE THREAD

**Issue by dvorapa** [LuminosoInsight/langcodes#21]
Hello, I've found your library when looking for some good source to get long lang codes from the short ones (cs -> cs_CZ). I've tried tag_match_score function, but for middle Europe languages it does not work as expected. See the following table:

Languages | Expected | Outputted
------------ | ------------- | -------------
cs - sk | 86-95 | 16
cs - pl | 76-85 | 16
sk - pl | 76-85 | 16
cs - hr | 76-85 | 16

**Comment by rspeer** [comment]
Unfortunately, Unicode's language-matching function knows very little about central European languages. Here's the table (which has been restated in terms of "distance", the opposite of match score): https://www.unicode.org/cldr/charts/33/supplemental/language_matching.html

I know that Unicode's function is woefully incomplete, but it at least gives you _some_ way to match different language codes. I just implement the function; I'm not forging ahead with my own sociolinguistic research.
