### ISSUE TITLE
No recent ISO 639-3 codes

### ISSUE THREAD

**Issue by kbulygin** [LuminosoInsight/langcodes#23]
First of all, thanks for the library. 

I've just noticed that the ISO 639-3 code `hyw` (https://iso639-3.sil.org/code/hyw) is missing. Its "Effective Date" is 2018-01-23, but in the latest version of `langcodes` (https://pypi.org/project/langcodes/1.4.1/, 2018-03-07), `langcodes.get('hyw').language_name()` returns just `'hyw'`.

Is that because the underlying "CLDR and the IANA subtag registry" (`README.md`) are not updated yet? (A relevant issue: #11.)

**Comment by rspeer** [comment]
This has been fixed by now, with newer versions updating the CLDR and IANA data.
