### ISSUE TITLE
zh-HK and zh_HK are normalized differently

### ISSUE THREAD

**Issue by cnvandev** [LuminosoInsight/langcodes#24]
Noticed a bit of an inconsistency in how langcodes is doing language replacements, so that normalizing `zh-HK` and `zh_HK` aren't normalized the same:

     >>> import langcodes
     >>> langcodes.get("zh-HK")
     Language.make(language='zh', script='Hant', region='HK')
     >>> langcodes.get("zh_HK")
     Language.make(language='zh', region='HK')

Langcodes currently [lowercases the tags](https://github.com/LuminosoInsight/langcodes/blob/master/langcodes/__init__.py#L240) to do the normalization, I think this would be fixed if it used [`tag_parser.normalize_characters()`](https://github.com/LuminosoInsight/langcodes/blob/master/langcodes/tag_parser.py#L91) instead of just `.lower()`, then they would both pick up the normalization.

**Comment by rspeer** [comment]
Good catch and a good solution, thanks.
