### ISSUE TITLE
[minor] Releases not tagged

### ISSUE THREAD

**Issue by AngusP** [LuminosoInsight/langcodes#32]
Hey, noiced that v2.0.0 and v1.4.1 are released on PyPi but not in the repo as tags/releases https://pypi.org/project/langcodes/#history

**Comment by mweinelt** [comment]
Same issue with 3.0,0. We'd like to run the tests when packaging this and since they are only on GitHub we kinda have to rely on tags to be able to automatically update.

**Comment by rspeer** [comment]
Sorry about that. I've tagged 3.1.
