### ISSUE TITLE
List of territories by language code

### ISSUE THREAD

**Issue by kaime** [LuminosoInsight/langcodes#40]
Given a language code, I'd like to get a list of all territories where that language is being used. For example, for language `it` (italian), it should return: `IT, SM, CH` (Italy, San Marino, Switzerland).

Is there a way I could do that with this package?

**Comment by rspeer** [comment]
That seems out of scope for langcodes, but the information you're looking for can be looked up fairly directly in CLDR itself. Get `cldr-common-38.1.zip` from http://unicode.org/Public/cldr/38.1/, and you'll find it in `common/supplemental/supplementalData.xml`.

**Comment by kaime** [comment]
Thanks for the info, rspeer.
